Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("cXenseParse:recs:sba-contenttype","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",dataDefName:"m_content_type",collection:"PageLevel",source:"Manage",priv:"false"},{id:"16641"})},16641)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("og:site_name","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",dataDefName:"og_site_name",collection:"PageLevel",source:"Manage",priv:"false"},{id:"16302"})},16302)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("cXenseParse:pageclass","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:Bootstrapper.data.afterEnsightenCompleteTrigger,dataDefName:"m_article_type",collection:"PageLevel",source:"Manage",priv:"false"},{id:"5579"})},
5579)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return window.sData.social.provider}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:function(){return Bootstrapper.data.triggerPromise(function(){try{return window.sData.social.provider||null}catch(e){return null}},null)},dataDefName:"socialProvider",collection:"PageLevel",
source:"Manage",priv:"false"},{id:"10764"})},10764)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("search_api_views_fulltext","param")}catch(e){return"error"}},transform:function(v){return v},load:"page",dataDefName:"food_search_term",collection:"PageLevel",source:"Manage",priv:"false"},{id:"6276"})},6276)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.on("click","#capture_signin_link",function(){Bootstrapper.ensEvent.trigger("Login Click from Ondemand",this)},true)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.dataManager=function(){var e={data:{},add:function(a){"object"==typeof a&&a.id&&(a.get=function(a){return Bootstrapper.dataManager.getDataElement(this.id,a)},this.data[a.id]=a)},getObj:function(a){return a?e.data[a]:e.data},getDataElement:function(a,d){var b=this.data[a].data,c;if("object"==typeof b)return b=b[d],"string"==typeof b.get?(c=eval(b.get),"string"==
typeof b.mod&&""!==b.mod?(b="(function(){ return "+(""===b.mod?"this":b.mod)+";})",c=eval(b).call(c)):c="function"==typeof b.mod?b.mod.call(c,c):c):"function"==typeof b.get&&(c=b.get.call(this.data[a]),"string"==typeof b.mod&&""!==b.mod?(b="(function(){ return "+(""===b.mod?"this":b.mod)+";})",c=eval(b).call(c)):c="function"==typeof b.mod?b.mod.call(c,c):c),c},getDataLayer:function(a){var d={},b=this.data[a].data;for(key in b)try{d[key]=this.getDataElement(a,key)}catch(c){d[key]=null}return d},getAllData:function(){var a=
this.data,d={_d:{}},b;for(b in a){d._d[b]={};var a=this.getDataLayer(b),c;for(c in a)d[c]=a[c],d._d[b][c]=a[c]}return d},getData:function(a){return a?this.getDataLayer(a):this.getAllData()},addDataElement:function(a,d,b){"object"==typeof this.data[a]&&("string"==typeof d&&"object"==typeof b)&&(this.data[a].data[d]=b)}};return{push:function(a){e.add(a)},getObj:function(a){return e.getObj(a)},getData:function(a){return e.getData(a)},getDataElement:function(a,d){return e.getDataElement(a,d)},addDataElement:function(a,
d,b){return e.addDataElement(a,d,b)}}}()},2835316,199874);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("og:title","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:Bootstrapper.data.afterEnsightenCompleteTrigger,dataDefName:"m_title",collection:"PageLevel",source:"Manage",priv:"false"},{id:"4966"})},4966)},-1,
-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return window.sData.social.url}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:function(){return Bootstrapper.data.triggerPromise(function(){try{return window.sData.social.url||null}catch(e){return null}},null)},dataDefName:"socialURL",collection:"PageLevel",source:"Manage",
priv:"false"},{id:"10765"})},10765)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("og:article:author","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:Bootstrapper.data.afterEnsightenCompleteTrigger,dataDefName:"m_author",collection:"PageLevel",source:"Manage",priv:"false"},{id:"5578"})},
5578)},-1,-1);
Bootstrapper.bindDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.data.resolve(["4966","16302","5578"],function(manage_4966,manage_16302,manage_5578){var loc=window.location.href;if(loc.indexOf("/api/audio_player")==-1&&loc.indexOf("/matchcentre-iframe")==-1&&loc.indexOf("/video/single/")==-1&&window.location.host.indexOf("sbs")!==-1){var _sf_async_config=window._sf_async_config=window._sf_async_config||{};_sf_async_config.uid=58103;
_sf_async_config.domain="sbs.com.au";_sf_async_config.playerdomain="sbs.com.au";_sf_async_config.useCanonical=true;try{if(typeof window.SBS!="undefined"&&typeof window.SBS.tokenValues!="undefined"){_sf_async_config.title=manage_4966;_sf_async_config.sections=manage_16302;_sf_async_config.authors=manage_5578}if(loc.indexOf(".au/ondemand/")>0)_sf_async_config.sections="ondemand"}catch(e){}window._sf_endpt=(new Date).getTime();Bootstrapper.insertScript("//static.chartbeat.com/js/chartbeat_video.js")}})},
2835309,323590);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("cXenseParse:recs:sba-alc_language","meta")}catch(e){return"error"}},transform:function(v){return v},load:"page",trigger:Bootstrapper.data.afterEnsightenCompleteTrigger,dataDefName:"m_language",collection:"PageLevel",source:"Manage",priv:"false"},
{id:"6270"})},6270)},-1,-1);